# Generated by Django 5.0.1 on 2025-03-03 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listitem',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
