# Generated by Django 5.0.1 on 2025-01-28 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='listItems',
        ),
        migrations.AddField(
            model_name='list',
            name='listItems',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lists.listitem'),
        ),
    ]
