# Generated by Django 5.1.3 on 2025-01-09 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
