# Generated by Django 5.1.3 on 2025-01-09 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_alter_list_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='created',
            field=models.DateField(auto_now_add=True, default='n/a'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='list',
            name='last_updated',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='list',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
