# Generated by Django 5.1.3 on 2025-01-09 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0002_list_ordered'),
    ]

    operations = [
        migrations.DeleteModel(
            name='List',
        ),
        migrations.DeleteModel(
            name='ListItem',
        ),
    ]
